//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;



namespace TpPW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carpeta
    {
        public int IdCarpeta { get; set; }

        public Nullable<int> IdUsuario { get; set; }
        

        [Required(ErrorMessage = "{0} es obligatorio")]
        [MaxLength(50, ErrorMessage = "El {0} no puede superar los {1} caracteres")]
        public string Nombre { get; set; }

       
        [MaxLength(200, ErrorMessage = "El {0} no puede superar los {1} caracteres")]
        public string Descripcion { get; set; }
        public System.DateTime FechaCreacion { get; set; }

        
        
    
        public virtual Usuario Usuario { get; set; }
    }



}
