//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;


namespace TpPW.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Tarea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarea()
        {
            this.ArchivoTarea = new HashSet<ArchivoTarea>();
            this.ComentarioTarea = new HashSet<ComentarioTarea>();
        }

        public int IdTarea { get; set; }
        public int IdCarpeta { get; set; }
        public int IdUsuario { get; set; }

        [Required]
        [StringLength (50, ErrorMessage = "El {0} no puede superar los {1} caracteres")]
        public string Nombre { get; set; }

        [StringLength(200, ErrorMessage = "El {0} no puede superar los {1} caracteres")]
        public string Descripcion { get; set; }

        public decimal? EstimadoHoras { get; set; }

        public Nullable<System.DateTime> FechaFin { get; set; }

        [Display (Name="Prioridad")]
        public short Prioridad { get; set; }
        public short Completada { get; set; }
        public System.DateTime FechaCreacion { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchivoTarea> ArchivoTarea { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentarioTarea> ComentarioTarea { get; set; }

        public virtual Usuario Usuario { get; set; }



        public IEnumerable<SelectListItem> ListaPrioridad { get; set; }
        public IEnumerable<SelectListItem> IdDeCarpeta { get; set; }
    }
}
